Resolve "CMake don't throw error when building examples and certain libraries are missing."

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -140,6 +140,13 @@ build:cmake-rocm:
       -D CMAKE_HIP_ARCHITECTURES="$GPU_TARGETS"
       -D CMAKE_CXX_FLAGS="$CXX_FLAGS"
       -D CMAKE_HIP_FLAGS="$HIP_FLAGS"
+      | tee cmake_log.txt
+    # check if all dependencies were found
+    - |-
+      if grep -q "Could NOT find" cmake_log.txt; then
+          echo "Some CMake libraries could not be found"
+          exit 1
+      fi
     - cmake --build $CI_PROJECT_DIR/build
 
 build:cmake-cuda:
@@ -155,6 +162,13 @@ build:cmake-cuda:
       -D GPU_RUNTIME=CUDA
       -D CMAKE_CXX_FLAGS="$CXX_FLAGS"
       -D CMAKE_CUDA_FLAGS="$CUDA_FLAGS"
+      | tee cmake_log.txt
+    # check if all dependencies were found
+    - |-
+      if grep -q "Could NOT find" cmake_log.txt; then
+          echo "Some CMake libraries could not be found"
+          exit 1
+      fi
     - cmake --build $CI_PROJECT_DIR/build
 
 .test:
@@ -229,5 +243,10 @@ test:rocm-windows-cmake:
       -D CMAKE_HIP_ARCHITECTURES=gfx1030
       -D CMAKE_RC_COMPILER="C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/rc.exe"
       -D CMAKE_TOOLCHAIN_FILE="C:/Tools/Microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake"
+      | Tee-Object -filepath cmake_log.txt
+    - |-
+      if (Select-String -Path cmake_log.txt -Pattern "Could NOT find") {
+          throw "Some cmake libraries are missing"
+      }
     - cmake --build "$CI_PROJECT_DIR/build"
     - cd "$CI_PROJECT_DIR/build" && ctest --output-on-failure
