Develop Stream: update to ROCm 6.1 (#138)
* Resolve "Update to ROCm 6.1"

* Fixed broken URLs

---------

Co-authored-by: Robin Voetter <robin@streamhpc.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,6 +1,6 @@
 # MIT License
 #
-# Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All rights reserved.
+# Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All rights reserved.
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -37,6 +37,13 @@ variables:
   #   argument unused during compilation: '--rtlib=compiler-rt'
   CXX_FLAGS: "-Wno-unused-command-line-argument -Wall -Wextra -Werror"
   HIP_FLAGS: "-Wno-unused-command-line-argument -Wall -Wextra -Werror"
+  # Keep in sync with ROCM_VERSION in Dockerfiles/hip-libraries-cuda-ubuntu.Dockerfile
+  # and Dockerfiles/hip-libraries-rocm-ubuntu.Dockerfile
+  DOCKER_ROCM_VERSION: 6.1.0
+  DOCKER_HIP_LIBRARIES_ROCM_TAG: rocm-ubuntu-${DOCKER_ROCM_VERSION}
+  DOCKER_HIP_LIBRARIES_CUDA_TAG: cuda-ubuntu-${DOCKER_ROCM_VERSION}
+  DOCKER_HIP_LIBRARIES_ROCM: $DOCKER_TAG_PREFIX:$DOCKER_HIP_LIBRARIES_ROCM_TAG
+  DOCKER_HIP_LIBRARIES_CUDA: $DOCKER_TAG_PREFIX:$DOCKER_HIP_LIBRARIES_CUDA_TAG
 
 stages:
   - lint
@@ -44,7 +51,7 @@ stages:
   - test
 
 clang-format:
-  image: $DOCKER_TAG_PREFIX:rocm-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_ROCM
   stage: lint
   needs: []
   tags:
@@ -60,7 +67,7 @@ clang-format:
     - Scripts/CodeFormat/check_format.sh $CI_MERGE_REQUEST_DIFF_BASE_SHA --binary "$CLANG_FORMAT"
 
 copyright-date:
-  image: $DOCKER_TAG_PREFIX:rocm-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_ROCM
   stage: lint
   needs: []
   tags:
@@ -88,7 +95,7 @@ copyright-date:
     - >-
       /kaniko/executor
       --context "${CI_PROJECT_DIR}/Dockerfiles"
-      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/hip-libraries-${TAG}.Dockerfile"
+      --dockerfile "${CI_PROJECT_DIR}/Dockerfiles/${DOCKERFILE}"
       --destination "docker.io/${DOCKER_TAG_PREFIX}:${TAG}"
       ${NO_PUSH}
   rules:
@@ -103,20 +110,22 @@ build:rocm-ubuntu-dockerfile:
   extends:
     - .build:dockerfiles
   variables:
-    TAG: rocm-ubuntu
+    DOCKERFILE: hip-libraries-rocm-ubuntu.Dockerfile
+    TAG: $DOCKER_HIP_LIBRARIES_ROCM_TAG
 
 build:cuda-ubuntu-dockerfile:
   extends:
     - .build:dockerfiles
   variables:
-    TAG: cuda-ubuntu
+    DOCKERFILE: hip-libraries-cuda-ubuntu.Dockerfile
+    TAG: $DOCKER_HIP_LIBRARIES_CUDA_TAG
 
 ########################
 # Ubuntu make          #
 ########################
 
 build:make-rocm:
-  image: $DOCKER_TAG_PREFIX:rocm-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_ROCM
   stage: build
   extends:
     - .rules:build
@@ -127,7 +136,7 @@ build:make-rocm:
     - cd $CI_PROJECT_DIR && make CXXFLAGS="$HIP_FLAGS" -j $(nproc)
 
 build:make-cuda:
-  image: $DOCKER_TAG_PREFIX:cuda-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_CUDA
   stage: build
   extends:
     - .rules:build
@@ -151,7 +160,7 @@ build:make-cuda:
       - $CI_PROJECT_DIR/build
 
 build:cmake-rocm:
-  image: $DOCKER_TAG_PREFIX:rocm-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_ROCM
   extends:
     - .build:cmake
     - .gpus:rocm-gpus
@@ -175,28 +184,28 @@ build:cmake-rocm:
     - cmake --install $CI_PROJECT_DIR/build --prefix $CI_PROJECT_DIR/install
 
 build:cmake-cuda:
- image: $DOCKER_TAG_PREFIX:cuda-ubuntu
- extends:
-   - .build:cmake
- tags:
-   - build
- script:
-   - cmake
-     -S $CI_PROJECT_DIR
-     -B $CI_PROJECT_DIR/build
-     -D GPU_RUNTIME=CUDA
-     -D CMAKE_CXX_FLAGS="$CXX_FLAGS"
-     -D CMAKE_CUDA_FLAGS="$CUDA_FLAGS"
-     -D CMAKE_MODULE_PATH=/opt/rocm/lib/cmake/hip
-     2>&1 | tee cmake_log.txt
-   # check if all dependencies were found
-   - |-
-     if grep -qi "could not find" cmake_log.txt; then
-         echo "Some CMake libraries could not be found"
-         exit 1
-     fi
-   - cmake --build $CI_PROJECT_DIR/build
-   - cmake --install $CI_PROJECT_DIR/build --prefix $CI_PROJECT_DIR/install
+  image: $DOCKER_HIP_LIBRARIES_CUDA
+  extends:
+    - .build:cmake
+  tags:
+    - build
+  script:
+    - cmake
+      -S $CI_PROJECT_DIR
+      -B $CI_PROJECT_DIR/build
+      -D GPU_RUNTIME=CUDA
+      -D CMAKE_CXX_FLAGS="$CXX_FLAGS"
+      -D CMAKE_CUDA_FLAGS="$CUDA_FLAGS"
+      -D CMAKE_MODULE_PATH=/opt/rocm/lib/cmake/hip
+      2>&1 | tee cmake_log.txt
+    # check if all dependencies were found
+    - |-
+      if grep -qi "could not find" cmake_log.txt; then
+          echo "Some CMake libraries could not be found"
+          exit 1
+      fi
+    - cmake --build $CI_PROJECT_DIR/build
+    - cmake --install $CI_PROJECT_DIR/build --prefix $CI_PROJECT_DIR/install
 
 ########################
 # Ubuntu Tests         #
@@ -207,10 +216,10 @@ build:cmake-cuda:
   extends:
     - .rules:test
   script:
-    - cd $CI_PROJECT_DIR/build && ctest --output-on-failure
+    - cd $CI_PROJECT_DIR/build && ctest --output-on-failure --parallel 8
 
 test:rocm:
-  image: $DOCKER_TAG_PREFIX:rocm-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_ROCM
   extends:
     - .test
     - .gpus:rocm
@@ -218,7 +227,7 @@ test:rocm:
     - build:cmake-rocm
 
 test:cuda:
-  image: $DOCKER_TAG_PREFIX:cuda-ubuntu
+  image: $DOCKER_HIP_LIBRARIES_CUDA
   extends:
     - .test
     - .gpus:nvcc
@@ -386,7 +395,7 @@ test:windows-nvcc-vs:
     # So for now, just add the library path here.
     - $env:PATH = "${env:HIP_PATH}\bin;" + $env:PATH
     - cd "$CI_PROJECT_DIR/build"
-    - ctest --output-on-failure --timeout 15
+    - ctest --output-on-failure --timeout 15 --parallel 8
     - cmake --install "$CI_PROJECT_DIR/build" --prefix "$CI_PROJECT_DIR/install"
   needs: []
 
